from pathlib import Path

import streamlit as st
import joblib
import json
import pandas as pd


# ==========================================
# 1. Paths
# ==========================================

BASE_DIR = Path(__file__).resolve().parent.parent

ARTIFACTS_DIR = BASE_DIR / "artifacts"


# ==========================================
# 2. Load Model
# ==========================================

model = joblib.load(
    ARTIFACTS_DIR / "flight_price_model.joblib"
)


# ==========================================
# 3. Load Metadata
# ==========================================

with open(
    ARTIFACTS_DIR / "flight_price_model.meta.json",
    "r",
    encoding="utf-8"
) as f:
    metadata = json.load(f)


# ==========================================
# 4. Page Configuration
# ==========================================

st.set_page_config(
    page_title="Flight Price Prediction",
    page_icon="✈️",
    layout="centered"
)


# ==========================================
# 5. Title
# ==========================================

st.title("✈️ Flight Price Prediction")

st.write(
    "Predict the estimated price of a flight using Machine Learning."
)


# ==========================================
# 6. Flight Information
# ==========================================

st.subheader("Flight Information")


airline = st.selectbox(
    "Airline",
    metadata["categories"]["airline"]
)


flight = st.text_input(
    "Flight Number",
    placeholder="Example: UK-995"
)


source_city = st.selectbox(
    "Source City",
    metadata["categories"]["source_city"]
)


destination_city = st.selectbox(
    "Destination City",
    metadata["categories"]["destination_city"]
)


departure_time = st.selectbox(
    "Departure Time",
    metadata["categories"]["departure_time"]
)


arrival_time = st.selectbox(
    "Arrival Time",
    metadata["categories"]["arrival_time"]
)


stops = st.selectbox(
    "Number of Stops",
    metadata["categories"]["stops"]
)


flight_class = st.selectbox(
    "Class",
    metadata["categories"]["class"]
)


# ==========================================
# 7. Numerical Variables
# ==========================================

duration_min, duration_max = metadata["ranges"]["duration"]

days_left_min, days_left_max = metadata["ranges"]["days_left"]


duration = st.number_input(
    "Duration (hours)",
    min_value=float(duration_min),
    max_value=float(duration_max),
    value=float(duration_min),
    step=0.1
)


days_left = st.number_input(
    "Days Left",
    min_value=int(days_left_min),
    max_value=int(days_left_max),
    value=int(days_left_min),
    step=1
)


# ==========================================
# 8. Prediction
# ==========================================

if st.button("🔮 Predict Price"):

    if flight.strip() == "":
        st.warning("Please enter the flight number.")

    else:

        # Create DataFrame
        input_data = pd.DataFrame({
            "airline": [airline],
            "flight": [flight],
            "source_city": [source_city],
            "departure_time": [departure_time],
            "stops": [stops],
            "arrival_time": [arrival_time],
            "destination_city": [destination_city],
            "class": [flight_class],
            "duration": [duration],
            "days_left": [days_left]
        })


        # Make prediction
        prediction = model.predict(input_data)

        price = prediction[0]


        # Display prediction
        st.success(
            f"💰 Estimated Flight Price: {price:.2f}"
        )

        st.info(
            "This price is an estimation generated by the Machine Learning model."
        )


# streamlit run app/app.py   use this commende to run 